name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Get package info from tag
        id: package_info
        run: |
          TAG=${{ github.ref_name }}
          PACKAGE_NAME=$(echo $TAG | cut -d'@' -f1)
          echo "package_name=$PACKAGE_NAME" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: bun install

      - name: Build package
        run: bun run build --filter=${{ steps.package_info.outputs.package_name }}

      - name: Configure npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm config set access public

      - name: Publish package
        run: |
          cd packages/${{ steps.package_info.outputs.package_name }}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
